Return remote info info in run-metadata endpoint
vimc/orderly.server pull request #36
Opened 2020-09-18 10:10 UTC by r-ash

This PR will
* Include remote info as `remotes` section in `run-metadata` response

This is the remote where dependencies should be resolved from when running a report.

I think if running on production then users probably shouldn't be able to resolve dependencies from science but I don't know where that logic belongs (presumably in same place as we have the logic that says if production then don't allow choosing git branch)

2020-09-22 11:38 UTC, richfitz requested changes
The logic for this needs to be done via an update to the `$server_options()` method on the config object, but I do not think that this can be passed through to a report that is being run. I am confused about who needs this?

2020-09-22 15:07 UTC, r-ash commented
> The logic for this needs to be done via an update to the `$server_options()` method on the config object, but I do not think that this can be passed through to a report that is being run. I am confused about who needs this?

The use case here is "As a scientist I want to be able to run a report on science resolving dependencies from production" i.e. filling the same role as the current `remote` arg to `orderly_run`. I think `server_options` only returns info about the current server so on production, it only has info about production so isn't quite what we want. 

The `primary` key on the config is important though e.g. https://github.com/vimc/orderly/blob/9a0abff240300b881f9dfd85f401a02e8f1c2725/tests/testthat/test-config.R#L128

I think we want really if on science then this returns `science` or `production` but if on production as it is the primary remote it shouldn't be able to resolve dependencies from other systems. Maybe this needs a new function

2020-09-22 15:11 UTC, richfitz commented
> As a scientist I want to be able to run a report on science resolving dependencies from production

This requires support in orderly_run_remote (and I presume throughout orderly.server) in order to work, I believe then. The `orderly_run_remote` function takes a `remote` argument, but that's the server that it runs on, not which remote is available. We'll need to add another argument to that function like "remote_remote" (!😱 !), and we should think more generally about how these things get configured too.

2020-09-22 16:05 UTC, r-ash commented
> > As a scientist I want to be able to run a report on science resolving dependencies from production
> 
> This requires support in orderly_run_remote (and I presume throughout orderly.server) in order to work, I believe then. The `orderly_run_remote` function takes a `remote` argument, but that's the server that it runs on, not which remote is available. We'll need to add another argument to that function like "remote_remote" (!scream !), and we should think more generally about how these things get configured too.

`orderly_run_remote` isn't the function that the front end will use though? I think still a problem - atm orderly.server uses the CLI to run reports which doesn't take a remote arg so that won't work. But in the refactor moving to use `orderly_run_internal` which does take the arg. So it shouldn't be that difficult to add once the refactor is done? If that's the case I wonder if we should just put this down and make a ticket to do it as an enhancement once the main feature is built.

2020-09-24 10:46 UTC, r-ash commented
Closing this as more complicated than I originally thought. Check the issue for more details

2020-09-24 10:46 UTC, closed without merging