vimc-4306: Ensure spec is up to date
vimc/orderly.server pull request #91
Opened 2022-02-11 17:33 UTC by r-ash

* Updates the spec including adding notes about workflow endpoints and new statuses
* Add a PR template to remind us to keep it up to date in the future

2022-02-22 13:49 UTC, richfitz requested changes
There's a bigger question here about how we keep this accurate - I don't expect that these responses all are current or correct and there's no real way of knowing. It would be good to automate testing this, but that would be probably best done in porcelain?  Happy to merge this once the small changes are made but would be curious for your thoughts on a longer term solution

2022-02-22 13:49 UTC, richfitz commented on inst/schema/spec.md
> +            "version": 20210211-143212-98c45632
This is invalid json and requires quotes (see below too)

2022-02-22 13:49 UTC, richfitz commented on .github/pull_request_template.md
> +- [ ] spec.md has been updated or doesn't need to updated
Is there anything we can add that will process the spec programmatically? I feel we've done this elsewhere. Alternatively  we should add support in porcelain for doing openapi/swagger as that will allow examples to be included and tested more easily

2022-02-22 13:49 UTC, richfitz commented on inst/schema/spec.md
> +          "> png("mygraph.png")",
Escape quotes

2022-02-22 15:53 UTC, r-ash commented
Agree would be good if we had some testing that this was correct, I also expect it is not up to date and as we've seen is hard to remember to keep it up to date! Having some swagger documentation with examples would be a good step there. I also like the look of [pact](https://docs.pact.io/) which is based around contract testing but generates docs for you too. It would be more like orderly-web describes the contract that orderly.server needs to provide and then we have contract tests which make sure our API meets their needs. I think focused on teams who might have multiple consumers of their API instead of us where we just have 1 so might be overkill. But would probably simplify testing for web devs.

2022-02-25 10:11 UTC, richfitz approved these changes

2022-02-25 10:11 UTC, merged